### ISSUE TITLE
Get error after type: ~/.siriproxy# siriproxy bundle or siriproxy bundle 

### ISSUE THREAD

**Issue by heydemar** [elvisimprsntr/siriproxy-rpi#1]
I get a error after type in siriproxy bundle 

root@Hey-Net-Rasp01:~/.siriproxy# siriproxy bundle
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'siriproxy-rpi (>= 0) ruby' in the gems available on this machine.

root@Hey-Net-Rasp01:~# siriproxy bundle
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'siriproxy-rpi (>= 0) ruby' in the gems available on this machine.

**Comment by elvisimprsntr** [comment]
I'm guessing that you tied to configure siriproxy-rpi as a gem in the config.yml file.  It's not released as a gem.

**Comment by elvisimprsntr** [comment]
don't run the siriproxy bundle command from within the .siriproxy folder.  do it from the the login directory

**Comment by heydemar** [comment]
This is my config.yml:

listen: 192.168.178.220
port: 443
log_level: 1

#Create an array of DNS servers for use by internal DNS server and resolving guzzoni.apple.com
upstream_dns: [8.8.8.8, 8.8.4.4]

#Set your computer's IP for use by the internal DNS server

# server_ip: 192.168.1.100

#Set effective user when running as root. Supply a non-privileged user (such as 'nobody')

# user: nobody

plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

   # - name: 'PiFace'
   #   path: '~/plugins/siriproxy-piface'
   #   camurls:  { 'garage': 'http://deko-ideen.net/wp-content/uploads/2012/11/Moderne-Organisation-in-der-grosser-   Garage.jpg'} #URLs of IP camera image.

```
- name: 'RPi'
```

      path: '~/plugins/siriproxy-rpi'

```
#- name: 'PictureJokes'
#  path: '~/plugins/siriproxy-picturejokes'

#- name: 'Example'
#  path: './plugins/siriproxy-example'

# - name: 'Thermostat'
#   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
#   host: '192.168.2.71'
```

**Comment by elvisimprsntr** [comment]
It's tough to tell if your config.yml is properly formatted, because the MD language messes with the formatting.     Unfortunately, the config.yml file entries must be properly formatted and in particular columns.  I suspect that's the problem.  I suggest you compare with the an original unmodified version.

**Comment by elvisimprsntr** [comment]
again, try running the `siriproxy bundle` from the default login directory.

**Comment by heydemar** [comment]
My config file is okay.
The formatting is automatically converted here unfortunately.

SiriProxy-piface works without problems but siriproxy-rpi not :(

root@Hey-Net-Rasp01:~# siriproxy bundle
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...

Could not find gem 'siriproxy-rpi (>= 0) ruby' in the gems available on this machine.

This is the error after starting the proxyserver:

root@Hey-Net-Rasp01:~# rvmsudo siriproxy server -d 192.168.178.220
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Could not find gem 'siriproxy-rpi (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.

**Comment by elvisimprsntr** [comment]
Humm...   The RPi plugin is simpler than PiFace.   Try moving the RPi configuration above the commented out PiFace.
