### ISSUE TITLE
How ca i start a command in a Plugin ? 

### ISSUE THREAD

**Issue by heydemar** [elvisimprsntr/siriproxy-rpi#3]
Hello,

i want to start this command in a Plugin:

root@Dres-Net-Rasp01:~# cd rcswitch-pi
root@Dres-Net-Rasp01:~/rcswitch-pi# ./send 11111 1 1

and 

root@Dres-Net-Rasp01:~/rcswitch-pi# ./send 11111 1 0

How do I have to enter this in for example your -rpi Plugin ? 

Thanks!!!!

**Comment by elvisimprsntr** [comment]
You have few options.  It all depends on if you want to capture the response from the command or not.  Here are some examples.  http://stackoverflow.com/questions/10224481/running-a-command-from-ruby-displaying-and-capturing-the-output

**Comment by heydemar** [comment]
Thanks, unfortunately that is somehow too complicated for me: (

**Comment by elvisimprsntr** [comment]
Pick up some ruby programming books.
