### ISSUE TITLE
Siriproxy doesn't working

### ISSUE THREAD

**Issue by OmurCeran** [elvisimprsntr/siriproxy-rpi#5]
Hi. I have problems with siriproxy when ı start siriproxy server. I uploaded 2 photos about siriproxy running.There are 2 differents between raspberry and network datas.Can you tell me where I make a mistake?.Besides that, When ı try to connect siriproxy server on the network , it answers me " plugins loaded:Example ".
![20160710_163625](https://cloud.githubusercontent.com/assets/20382793/16713882/1c37613c-46bd-11e6-956a-0dfe6b81845b.jpg)
![20160710_163753](https://cloud.githubusercontent.com/assets/20382793/16713889/4258bb36-46bd-11e6-87eb-f76b3dedea24.jpg)

**Comment by elvisimprsntr** [comment]
SiriProxy only works with iOS 6 

https://github.com/plamoni/SiriProxy
